### ISSUE TITLE
New extensions

### ISSUE THREAD

**Issue by frank1119** [gigperformer/gp-sdk#1]
First of all: This sdk is really helpful and very usable. Thanks.

Second: This is not an issue, but a question: How do I 'donate' my own extension?

I've written this extension that extends the scripting language with variables accessible from all script-types, so it is not exactly living up to reason for the possibility of writing extensions, being creating (graphical) interfaces for external hardware, as I understand it.

This is the location: https://github.com/frank1119/gp-globalvars

**Comment by sleiner** [comment]
Hi @frank1119,

> First of all: This sdk is really helpful and very usable.

thank you very much :-)

> How do I 'donate' my own extension?

As I see, you have made it publicly accessible under GPL, so in a sense, it is already donated to the community ☺️ If you want to, you can present your work in the [extensions category of the GP forums](https://community.gigperformer.com/c/gp-extensions/36) and get other people interested.

Or is there something else you had in mind when talking about donating it?

**Comment by frank1119** [comment]
Hi @sleiner ,

Thanks for your response. I just created a conversation in this category you mentioned.

> Or is there something else you had in mind when talking about donating it? 

Nope. I'm not trying to run a business (although I do not imply that that would be a bad thing). I just want to make it accessible to others. Maybe it is useful for somebody.

**Comment by frank1119** [comment]
Hi Simon,

Thanks for your response. I just created a conversation in this category
you mentioned.

Or is there something else you had in mind when talking about donating it?

Nope. I'm not trying to run a business (although I do not imply that that
would be a bad thing). I just want to make it accessible to others. Maybe
it is useful for somebody.

Kind regards,
Frank den Blaauwen
