### ISSUE TITLE
GigPerformerFunctions::switchToVariation redefinition

### ISSUE THREAD

**Issue by frank1119** [gigperformer/gp-sdk#12]
In GigPerformerFunctions.cpp the function switchToVariation is implemented like this

```
bool GigPerformerFunctions::switchToVariation(int variationIndex = 0)
{
    return switchToRackspace(-1, variationIndex);
}
```

However the part `int variationIndex = 0` counts as a redefinition, because it is in GigPerformerFunctions.h already defined as

```
bool switchToVariation(int variationIndex = 0);
```

Solution: Remove the `= 0` part in the implementation in GigPerformerFunctions.cpp

**Comment by sleiner** [comment]
Thanks, good catch!
