### ISSUE TITLE
Hard crash when using getSongKey() and getSongTempo()

### ISSUE THREAD

**Issue by daveboulden** [gigperformer/gp-sdk#18]
I'm not sure if this is an issue within this SDK implementation or if it exists in the source SDK also.

In the following code (adapted from https://github.com/daveboulden/gp-basic-songchooser) the compiled extension causes a hard crash as soon as I try to use either `getSongKey()` or `getSongTempo()`.

The test code I was using is: 

```c++
std::string LibMain::getSongListFromGP () {
    std::string songList = "";
    std::string thisSong;
    std::string thisArtist;
    std::string thisKey;
    double thisBPM;

    for (int i = 0; i < getSongCount(); ++i) {
        thisSong = getSongName(i);
        thisArtist = getArtistName(i);
        thisKey = getSongKey(i);
        thisBPM = getSongTempo(i);
        songList += "<li class='song-item' data-song-artist='" + thisSong + " | " + thisArtist + "'><a class='song-select' data-slot='" +
                    std::to_string(i) + "'>" + thisSong + " - " + thisArtist + "(" + thisKey + ")" "</a></li>";
    }

    return songList;
}
```

**Comment by daveboulden** [comment]
This has now been fixed in GP. I'm not sure if it will require any update to this version of the SDK or not.

**Comment by sleiner** [comment]
@daveboulden no SDK update will be required for this.
